version: "3"
services:
  windows:
    # image: dockurr/windows
    build:
      context: .
      dockerfile: Dockerfile.1
    container_name: windows
    # devices:
      # - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "winxp"
      KVM: "N"
      DEBUG: "Y"
      ARGUMENTS: "-accel hvf"
